
POST https://nextjs-router-light.vercel.app/api/room

{
    "name": "TOTAL"
}

###

GET https://nextjs-router-light.vercel.app/api/room


###

DELETE https://nextjs-router-light.vercel.app/api/room/b4339b8a-9bde-405b-a3f9-84cd4a9e153f


### readings
GET https://nextjs-router-light.vercel.app/api/readings?month=6&year=2024

### 
GET https://nextjs-router-light.vercel.app/api/reading/0a6cd673-b610-41e7-bcfb-5bda80f4e785

###
POST https://nextjs-router-light.vercel.app/api/reading

{
    "roomId": "efe6310e-8d5c-4b14-8d9b-aaeb46f3582a",
    "meterWater": 100.8,
    "meterLight": 200.8,
    "rent": 300,
    "year": 2024,
    "month": 6
}

###
DELETE https://nextjs-router-light.vercel.app/api/reading/be919445-6163-4b24-b60b-28c6f29b30aa

###

PUT https://nextjs-router-light.vercel.app/api/reading/0a6cd673-b610-41e7-bcfb-5bda80f4e785

{
    "roomId": "d8b70f92-df03-4335-b306-77c084504d2d",
    "meterWater": 400,
    "meterLight": 200,
    "rent": 350,
    "year": 2024,
    "month": 6
}

###
GET https://nextjs-router-light.vercel.app/api/setting

###
POST https://nextjs-router-light.vercel.app/api/setting

{
  "priceLight": 0.8,
  "priceWater": 5
}

