DELETE https://7gg7ughwve.execute-api.us-east-1.amazonaws.com/Prod/measure/1b48568c-00a0-46db-8d72-34966563a46a


###
GET https://7gg7ughwve.execute-api.us-east-1.amazonaws.com/Prod/measure/1b48568c-00a0-46db-8d72-34966563a46a

###
POST https://8h2klscw75.execute-api.us-east-1.amazonaws.com/Prod/measure

{
    "id": "0e44281d-0f05-494b-bb55-a928864868f7",
    "room": "104",
    "meterWaterCurrent": 300.8,
    "meterWaterBefore": 100.8,
    "meterLightCurrent": 400.8,
    "meterLightBefore": 100.8,
    "rent": 100.8,
    "year": 2024,
    "month": 1,
    "local": "HUAROCHIRI"
}

###

PUT https://7gg7ughwve.execute-api.us-east-1.amazonaws.com/Prod/measure/0e44281d-0f05-494b-bb55-a928864868f7

{
    "room": "104",
    "meterWaterCurrent": 300.8,
    "meterWaterBefore": 100.8,
    "meterLightCurrent": 400.8,
    "meterLightBefore": 100.8,
    "rent": 100.8,
    "year": 2024,
    "month": 2,
    "local": "HUAROCHIRI"
}

###
GET https://7gg7ughwve.execute-api.us-east-1.amazonaws.com/Prod/measure/search?local=HUAROCHIRI&year=2024&month=2
